# Generated by Django 5.1.6 on 2025-02-20 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_number', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('graph_type', models.CharField(choices=[('SD', 'Supply/Demand'), ('TR', 'Tax Revenue'), ('TS', 'Time Series'), ('CP', 'Comparison'), ('TB', 'Tax Bracket')], max_length=2)),
                ('data_points', models.JSONField()),
                ('interpretation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraphRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=50)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='chatbot.graphdata')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationships', to='chatbot.graphdata')),
            ],
        ),
    ]
